name: ext_video_player
description: Flutter plugin for displaying inline  with other Flutter
  widgets on Android, iOS and web. This plugin also supports playing youtube videos & RTMP Streams
version: 1.0.0
homepage: https://github.com/juniorkibirige/ext_video_player_new
repository: https://github.com/juniorkibirige/ext_video_player_new
issue_tracker: https://github.com/juniorkibirige/ext_video_player_new/issues?q=is%3Aopen

flutter:
  plugin:
    platforms:
      android:
        package: ext.videoplayer
        pluginClass: ExtVideoPlayerPlugin
      ios:
        pluginClass: FLTExtVideoPlayerPlugin
      web:
        default_package: video_player_web

dependencies:
  meta: ^1.3.0
  video_player_platform_interface: ^4.1.0

  # The design on https://flutter.dev/go/federated-plugins was to leave
  # this constraint as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint.
  # TODO(amirh): Revisit this (either update this part in the  design or the pub tool).
  # https://github.com/flutter/flutter/issues/46264
  video_player_web: ^2.0.1
  
  flutter:
    sdk: flutter
  
  http: ^0.13.3
  youtube_explode_dart: ^1.9.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  pigeon: ^0.3.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"
